FROM node:22-alpine

WORKDIR /app

COPY apps/backend/package.json ./
COPY apps/backend/yarn.lock ./

RUN corepack enable && yarn install

COPY apps/backend/ .

RUN npx prisma generate
EXPOSE 3000

CMD ["yarn", "start:dev"]